version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 5672:5672   # RabbitMQ
      - 15672:15672 # Management console
    environment:
      RABBITMQ_DEFAULT_USER: trampar
      RABBITMQ_DEFAULT_PASS: trampar-de-casa


  trampar-conteiner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  #URL https://localhost:9443
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  db:
      image: supabase/postgres
      ports:
        - "54322:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      restart: unless-stopped

volumes:
  data:
networks:
  local:
    driver: bridge
